import type { Article, ArticleType, Source } from './articles';

const reviewed = '2026-08-21';
const home: Source = { organisation: 'UK Health Security Agency', title: 'Beat the heat: keep cool at home checklist', url: 'https://www.gov.uk/government/publications/beat-the-heat-hot-weather-advice/beat-the-heat-keep-cool-at-home-checklist', type: 'official guidance', accessed: reviewed, supports: 'Shading, ventilation, reducing indoor heat and protecting people at higher risk.' };
const energy: Source = { organisation: 'US Department of Energy', title: 'Home cooling', url: 'https://www.energy.gov/energysaver/home-cooling-systems', type: 'official guidance', accessed: reviewed, supports: 'Fans, ventilation, evaporative cooling, air conditioning, shading and energy use.' };
const nhs: Source = { organisation: 'NHS', title: 'Heat exhaustion and heatstroke', url: 'https://www.nhs.uk/conditions/heat-exhaustion-heatstroke/', type: 'health guidance', accessed: reviewed, supports: 'Heat-illness symptoms, cooling actions and when to seek emergency help.' };
const dehydration: Source = { organisation: 'NHS', title: 'Dehydration', url: 'https://www.nhs.uk/conditions/dehydration/', type: 'health guidance', accessed: reviewed, supports: 'Dehydration risks, signs, fluids and when to get help.' };
const baby: Source = { organisation: 'NHS', title: 'Keeping your baby safe in the sun', url: 'https://www.nhs.uk/baby/first-aid-and-safety/safety/safety-in-the-sun/', type: 'health guidance', accessed: reviewed, supports: 'Keeping babies and young children cool, hydrated and out of direct sun.' };
const medicines: Source = { organisation: 'NHS Specialist Pharmacy Service', title: 'Heatwaves and medicines: assessing and managing patient risk', url: 'https://www.sps.nhs.uk/articles/heatwaves-and-medicines-assessing-and-managing-patient-risk/', type: 'health guidance', accessed: reviewed, supports: 'Medicine-related heat risk, storage, hydration and the need for individual clinical advice.' };

type Draft = { type: ArticleType; title: string; slug: string; answer: string; steps: string[]; concepts: string[]; source?: Source; showTool?: boolean };
const drafts: Draft[] = [
  { type: 'action', title: 'How to cool yourself quickly', slug: 'how-to-cool-yourself-quickly', answer: 'Move somewhere cooler, remove unnecessary layers, drink cool fluids, wet your skin and use moving air.', steps: ['Move out of direct sun or into the coolest available room.', 'Remove extra clothing and slow down.', 'Drink cool water regularly.', 'Apply cool water to exposed skin and use a fan.'], concepts: ['personal cooling', 'evaporation'], source: nhs },
  { type: 'action', title: 'How to ventilate a house at night', slug: 'how-to-ventilate-a-house-at-night', answer: 'Open safe windows after outside becomes cooler than inside and create a clear route for air through the home.', steps: ['Check that the outside air is cooler.', 'Open secure windows on different sides or levels.', 'Use an outward-facing fan at one opening if airflow is weak.', 'Close up again before outdoor temperatures rise.'], concepts: ['night ventilation', 'airflow'], showTool: true },
  { type: 'action', title: 'How to cool a bedroom before sleep', slug: 'how-to-cool-a-bedroom-before-sleep', answer: 'Keep daytime sun out, reduce heat sources, then flush the room with cooler evening air before bed.', steps: ['Shade the bedroom during the day.', 'Turn off hot equipment and lights.', 'Ventilate when outside cools.', 'Use light bedding and cool yourself as well as the room.'], concepts: ['solar gain', 'night ventilation'], showTool: true },
  { type: 'action', title: 'How to block heat from windows', slug: 'how-to-block-heat-from-windows', answer: 'Stop sunlight before it reaches the glass where possible; otherwise close pale blinds or lined curtains before direct sun arrives.', steps: ['Use an external shutter, awning or shade where practical.', 'Close internal coverings early.', 'Prioritise east, west and south-facing glazing.', 'Avoid blocking required ventilation or escape routes.'], concepts: ['solar gain', 'shading'] },
  { type: 'action', title: 'How to create cross-ventilation', slug: 'how-to-create-cross-ventilation', answer: 'Give cooler air one safe opening to enter and warm air another opening to leave.', steps: ['Open windows or doors on opposing sides.', 'Keep the path between them open.', 'Use smaller inlet and larger outlet openings if useful.', 'Only ventilate for cooling when outside is cooler.'], concepts: ['cross-ventilation', 'airflow'], showTool: true },
  { type: 'action', title: 'How to use cool water for personal cooling', slug: 'how-to-use-cool-water-for-personal-cooling', answer: 'Drink cool fluids and wet exposed skin; moving air over damp skin can increase cooling.', steps: ['Sip water regularly.', 'Spray or sponge exposed skin with cool water.', 'Use wrapped cold packs at the neck or armpits when helping someone with heat exhaustion.', 'Do not delay emergency help for possible heatstroke.'], concepts: ['evaporation', 'personal cooling'], source: nhs },
  { type: 'decision', title: 'Fan vs air cooler vs air conditioner', slug: 'fan-vs-air-cooler-vs-air-conditioner', answer: 'Choose a fan for personal comfort, an evaporative cooler mainly for dry air, and air conditioning when you need dependable room cooling and dehumidification.', steps: ['Fan: lowest cost, but does not refrigerate the room.', 'Air cooler: adds moisture and works best in dry conditions.', 'Air conditioner: actively removes heat and moisture, but costs more to buy and run.'], concepts: ['airflow', 'evaporation', 'refrigeration', 'humidity'], source: energy },
  { type: 'decision', title: 'Portable AC vs split AC', slug: 'portable-ac-vs-split-ac', answer: 'Portable AC is easier to add temporarily; a correctly sized split system is usually quieter and more efficient for repeated cooling.', steps: ['Choose portable when installation is not possible.', 'Choose split for regular, efficient cooling.', 'Seal portable exhaust-window gaps carefully.', 'Get professional sizing and installation advice.'], concepts: ['refrigeration', 'energy use'], source: energy },
  { type: 'decision', title: 'Blackout curtains vs blinds vs external shading', slug: 'blackout-curtains-vs-blinds-vs-external-shading', answer: 'External shading usually stops the most solar heat. Curtains and blinds still help, especially when closed before sunlight reaches the glass.', steps: ['Use external shutters or awnings for strongest protection.', 'Use close-fitting lined curtains when external changes are not possible.', 'Choose blinds for adjustable light and glare control.'], concepts: ['solar gain', 'shading'] },
  { type: 'decision', title: 'Air cooler vs dehumidifier', slug: 'air-cooler-vs-dehumidifier', answer: 'Use an evaporative air cooler only in relatively dry air. A dehumidifier can improve humid conditions but releases heat into the room.', steps: ['Check humidity before choosing.', 'Avoid evaporative coolers in already humid rooms.', 'Expect a dehumidifier to warm the air slightly.', 'Use AC when both active cooling and moisture removal are needed.'], concepts: ['humidity', 'evaporation'], source: energy },
  { type: 'decision', title: 'Window film vs blinds', slug: 'window-film-vs-blinds', answer: 'Solar-control film is a persistent glazing measure; blinds are adjustable and easier to change. External shade is often more effective than either.', steps: ['Check glass and warranty compatibility before applying film.', 'Use blinds when adjustable privacy and light matter.', 'Prioritise the windows receiving the strongest sun.'], concepts: ['solar gain', 'glazing'] },
  { type: 'decision', title: 'Pedestal fan vs tower fan vs desk fan', slug: 'pedestal-vs-tower-vs-desk-fan', answer: 'Choose by airflow, noise, space and placement—not shape alone. A pedestal fan usually offers flexible reach; desk fans suit one person; tower fans save floor width.', steps: ['Compare measured airflow and noise.', 'Choose a stable model with a useful speed range.', 'Place it where the airflow actually reaches people.'], concepts: ['airflow', 'personal cooling'], source: energy },
  { type: 'situation', title: 'How to cool an upstairs bedroom', slug: 'how-to-cool-an-upstairs-bedroom', answer: 'Block roof and window heat during the day, then use cooler night air to purge stored heat from the upper floor.', steps: ['Shade sunny windows early.', 'Keep the loft hatch closed unless it is designed for ventilation.', 'Open safe high and low windows after outside cools.', 'Sleep downstairs temporarily if it is significantly cooler.'], concepts: ['stack effect', 'thermal mass'] },
  { type: 'situation', title: 'How to cool a flat', slug: 'how-to-cool-a-flat', answer: 'Shade the sunniest glass, reduce heat made indoors and use safe ventilation when outside becomes cooler.', steps: ['Prioritise west- and south-facing windows.', 'Use the coolest room as a daytime refuge.', 'Coordinate cross-ventilation only where security and fire safety allow.', 'Use shared cooler spaces if the flat remains unsafe.'], concepts: ['solar gain', 'single-sided ventilation'] },
  { type: 'situation', title: 'How to cool a dormer room', slug: 'how-to-cool-a-dormer-room', answer: 'Dormers often receive strong roof and window heat, so early shading and night ventilation matter most.', steps: ['Shade roof and vertical glazing.', 'Reduce equipment heat.', 'Ventilate once outside is cooler.', 'Consider professional roof and insulation advice for repeated overheating.'], concepts: ['roof heat', 'solar gain'] },
  { type: 'situation', title: 'How to cool a room with one window', slug: 'how-to-cool-a-room-with-one-window', answer: 'Shade the window in sun, then use an outward-facing fan near it after outside cools while allowing replacement air to enter safely.', steps: ['Keep direct sun off the glass.', 'Open the internal door if cooler replacement air is available.', 'Place a fan near the window facing out.', 'Do not pull hotter outdoor air in during the day.'], concepts: ['single-sided ventilation', 'airflow'], showTool: true },
  { type: 'situation', title: 'How to cool a gaming room', slug: 'how-to-cool-a-gaming-room', answer: 'Reduce equipment power, remove hot exhaust air and cool the person; high-powered hardware can be a major indoor heat source.', steps: ['Use efficient performance settings or cap frame rates.', 'Keep computer vents clear.', 'Move warm exhaust toward a safe opening when outside is cooler.', 'Turn off unused displays and equipment.'], concepts: ['internal heat', 'airflow'] },
  { type: 'situation', title: 'How to cool a south-facing room', slug: 'how-to-cool-a-south-facing-room', answer: 'Shade the glass before sunlight enters, keep hotter daytime air out and ventilate after outdoor temperatures fall.', steps: ['Use external shade if possible.', 'Close internal coverings before the sun reaches the room.', 'Reduce indoor heat sources.', 'Night-purge the room when conditions allow.'], concepts: ['solar gain', 'shading'], showTool: true },
  { type: 'situation', title: 'Why is my bedroom still hot at night?', slug: 'why-is-my-bedroom-still-hot-at-night', answer: 'The roof, walls and furniture may be releasing heat stored during the day, while weak airflow prevents that heat escaping.', steps: ['Keep the next day’s heat out early.', 'Ventilate when outside is cooler.', 'Create an exit path for warm air.', 'Check loft, roof and window shading for persistent problems.'], concepts: ['thermal mass', 'night ventilation'] },
  { type: 'situation', title: 'Why is my room hotter than outside?', slug: 'why-is-my-room-hotter-than-outside', answer: 'Stored heat, sunlight through glass, equipment and weak ventilation can keep indoor temperature above the outdoor reading.', steps: ['Open safe windows when outside is cooler.', 'Use a fan to help warm air leave.', 'Turn off internal heat sources.', 'Continue ventilation long enough to cool the building fabric.'], concepts: ['thermal mass', 'internal heat'], showTool: true },
  { type: 'situation', title: 'How to keep a home cool while away', slug: 'how-to-keep-a-home-cool-while-away', answer: 'Leave safe shading in place, switch off avoidable heat sources and use only secure, designed ventilation.', steps: ['Close blinds or shutters on sun-facing windows.', 'Turn off unnecessary equipment.', 'Do not leave insecure windows open.', 'Use timed mechanical ventilation or cooling only if designed for unattended use.'], concepts: ['shading', 'security'] },
  { type: 'situation', title: 'Cooling a room without cross-ventilation', slug: 'cooling-a-room-without-cross-ventilation', answer: 'Prevent heat entering first, then use a fan at the available opening when outside is cooler and draw replacement air from the coolest safe adjacent space.', steps: ['Shade the window.', 'Open the internal door if appropriate.', 'Expel warm air with a fan after outside cools.', 'Use personal cooling while the room temperature falls.'], concepts: ['single-sided ventilation', 'personal cooling'], showTool: true },
  { type: 'science', title: 'How evaporative cooling works', slug: 'how-evaporative-cooling-works', answer: 'Water needs energy to evaporate. It takes some of that energy as heat from the water, air or skin around it.', steps: ['Evaporation is faster in dry air.', 'Moving air speeds evaporation.', 'Evaporative coolers add moisture, so performance falls as humidity rises.'], concepts: ['evaporation', 'latent heat'], source: energy },
  { type: 'science', title: 'Why humidity matters', slug: 'why-humidity-matters', answer: 'High humidity slows evaporation, making sweat less effective and evaporative coolers less useful.', steps: ['Relative humidity describes how close air is to saturation at its current temperature.', 'Warm humid air can feel more stressful than equally warm dry air.', 'Air conditioning can cool and remove moisture.'], concepts: ['humidity', 'evaporation'], source: energy },
  { type: 'science', title: 'What wet-bulb temperature means', slug: 'what-wet-bulb-temperature-means', answer: 'Wet-bulb temperature combines heat and moisture to show how much cooling evaporation can still provide.', steps: ['It rises when air is hotter or more humid.', 'It is not the same as ordinary air temperature.', 'Personal risk also depends on exposure, health, activity, clothing and access to cooling.'], concepts: ['wet bulb', 'humidity'], source: home },
  { type: 'science', title: 'How air conditioning works', slug: 'how-air-conditioning-works', answer: 'Air conditioning uses a refrigeration cycle to collect heat indoors and release it outdoors, while usually removing moisture.', steps: ['The evaporator absorbs indoor heat.', 'The compressor and refrigerant carry that heat.', 'The outdoor condenser releases it outside.', 'Closed windows help prevent cooled air escaping.'], concepts: ['refrigeration', 'dehumidification'], source: energy },
  { type: 'science', title: 'How cross-ventilation works', slug: 'how-cross-ventilation-works', answer: 'Pressure differences move air from one opening, through the building and out through another.', steps: ['Wind can drive flow across a home.', 'Warm rising air can support vertical flow.', 'Obstructions and small openings reduce exchange.', 'For cooling, incoming air should be cooler than indoor air.'], concepts: ['cross-ventilation', 'pressure'] },
  { type: 'science', title: 'Why houses stay hot after sunset', slug: 'why-houses-stay-hot-after-sunset', answer: 'Building materials absorb heat during the day and release it later, so indoor temperature can peak after outdoor temperature starts falling.', steps: ['Roofs and sunny walls store heat.', 'Heavy materials release it slowly.', 'Night ventilation helps only once outside is cooler.'], concepts: ['thermal mass', 'time lag'] },
  { type: 'science', title: 'Thermal mass explained', slug: 'thermal-mass-explained', answer: 'Thermal mass is a material’s ability to absorb and store heat. It can smooth temperature swings but also keep a home warm at night.', steps: ['Concrete, brick and stone store substantial heat.', 'Shading prevents that mass charging with unwanted summer heat.', 'Cool night air can discharge stored heat.'], concepts: ['thermal mass', 'heat capacity'] },
  { type: 'science', title: 'Solar gain explained', slug: 'solar-gain-explained', answer: 'Solar gain is heat added when sunlight reaches surfaces or passes through glass and is absorbed indoors.', steps: ['East windows gain morning sun.', 'West windows can drive late-day overheating.', 'External shade stops sunlight before it reaches the glass.'], concepts: ['solar gain', 'radiation'] },
  { type: 'science', title: 'Why external shading works', slug: 'why-external-shading-works', answer: 'External shade blocks solar energy before the window and room absorb it, which is usually more effective than dealing with the heat indoors.', steps: ['Awnings can shade high summer sun.', 'Shutters provide strong protection.', 'Trees and planting can provide seasonal shade where appropriate.'], concepts: ['shading', 'solar gain'] },
  { type: 'science', title: 'How sweating cools the body', slug: 'how-sweating-cools-the-body', answer: 'Sweat cools when it evaporates from skin; sweat that drips away without evaporating provides less cooling.', steps: ['Moving air can increase evaporation.', 'High humidity reduces it.', 'Sweating also loses water and salts, so hydration matters.'], concepts: ['sweating', 'evaporation'], source: dehydration },
  { type: 'science', title: 'Why colder water is not always better', slug: 'why-colder-water-is-not-always-better', answer: 'Cool water can provide effective relief without needing to be painfully icy; the best method is one a person can use safely and continuously.', steps: ['Cool skin with water and airflow.', 'Wrap cold packs rather than applying them directly.', 'For suspected heatstroke, call emergency services and follow their instructions.'], concepts: ['personal cooling', 'heat transfer'], source: nhs },
  { type: 'science', title: 'Why upstairs gets hotter', slug: 'why-upstairs-gets-hotter', answer: 'Upper rooms receive roof heat and often have less shade; warm air movement and limited escape paths can add to the problem.', steps: ['Shade upper-floor glazing.', 'Reduce roof and loft heat gains.', 'Use safe high-level ventilation when outside cools.'], concepts: ['roof heat', 'stack effect'] },
  { type: 'science', title: 'Why moving air feels cooler', slug: 'why-moving-air-feels-cooler', answer: 'Moving air replaces the warm air next to your skin and helps moisture evaporate, increasing body heat loss.', steps: ['The room thermometer may not change.', 'The effect is strongest when air can evaporate moisture.', 'Fans should be aimed where people benefit.'], concepts: ['airflow', 'evaporation'], source: energy },
  { type: 'safety', title: 'Signs of heatstroke', slug: 'signs-of-heatstroke', answer: 'Possible signs include confusion, poor coordination, seizure, loss of consciousness, very high temperature, fast breathing or hot skin without sweating. Call 999.', steps: ['Call 999 immediately.', 'Move the person to a cooler place if safe.', 'Cool them while waiting.', 'Follow the call handler’s instructions.'], concepts: ['heatstroke', 'emergency'], source: nhs },
  { type: 'safety', title: 'How to help someone who is overheating', slug: 'how-to-help-someone-overheating', answer: 'Move them somewhere cool, remove unnecessary clothing, give cool water if they can drink, cool their skin and stay with them.', steps: ['Start cooling immediately.', 'Contact NHS 111 if you need advice.', 'Call 999 for heatstroke signs or if they remain unwell after 30 minutes.'], concepts: ['first aid', 'heat illness'], source: nhs },
  { type: 'safety', title: 'When is a hot room dangerous?', slug: 'when-is-a-hot-room-dangerous', answer: 'There is no single indoor number that diagnoses danger. Risk depends on heat, humidity, duration, health, activity and whether cooling is available.', steps: ['Watch the people in the room, not only the thermometer.', 'Move higher-risk people to a cooler place early.', 'Act on heat-illness symptoms.', 'Follow local heat-health alerts.'], concepts: ['heat risk', 'vulnerability'], source: home },
  { type: 'safety', title: 'Helping an elderly person during hot weather', slug: 'helping-an-elderly-person-during-hot-weather', answer: 'Check in regularly, help keep their main room cool, make drinks accessible and make sure they know the signs of heat illness.', steps: ['Check their room and how they feel.', 'Help with shading and safe ventilation.', 'Place drinks within easy reach unless fluids are medically restricted.', 'Review medicine storage instructions and check again later.'], concepts: ['older people', 'care checklist'], source: home },
  { type: 'safety', title: 'Heat safety for babies and young children', slug: 'heat-safety-for-babies-and-young-children', answer: 'Keep babies and young children out of direct sun, use lightweight clothing, continue normal feeds and check them frequently.', steps: ['Never cover a pram with a blanket.', 'Keep babies under 6 months out of direct sunlight.', 'Continue breastfeeding as normal.', 'Seek medical advice if you are worried or see dehydration or heat-illness signs.'], concepts: ['babies', 'children'], source: baby },
  { type: 'safety', title: 'Heat and limited mobility', slug: 'heat-and-limited-mobility', answer: 'Bring cooling, drinks and help within reach before heat builds, and arrange regular contact if the person cannot move to a cooler space independently.', steps: ['Set up the coolest accessible room.', 'Keep water and a phone within reach.', 'Help adjust shading and airflow safely.', 'Plan who will check again and when.'], concepts: ['limited mobility', 'care planning'], source: home },
  { type: 'safety', title: 'Checking on someone during a heatwave', slug: 'checking-on-someone-during-a-heatwave', answer: 'Check the person, their room, access to drinks, medicines and their ability to get help—not just whether they answer the phone.', steps: ['Ask how they feel and look for heat-illness signs.', 'Check the coolest room and window shading.', 'Make drinks accessible.', 'Agree a specific time for the next check.'], concepts: ['care checklist', 'social isolation'], source: home },
  { type: 'safety', title: 'Dehydration and hot weather', slug: 'dehydration-and-hot-weather', answer: 'Hot weather increases fluid loss through sweating. Thirst, dark urine, reduced urination, dizziness and a dry mouth can be warning signs.', steps: ['Drink regularly.', 'Take extra care with babies, children and older adults.', 'Follow medical advice if fluids are restricted.', 'Get urgent help for serious symptoms.'], concepts: ['dehydration', 'hydration'], source: dehydration },
  { type: 'safety', title: 'Humidity and heat risk', slug: 'humidity-and-heat-risk', answer: 'Humidity reduces sweat evaporation, so the same air temperature can place more strain on the body when moisture is high.', steps: ['Use air conditioning or a cooler, less humid space if available.', 'Do not rely on an evaporative cooler in humid air.', 'Watch for symptoms and reduce exertion.'], concepts: ['humidity', 'heat risk'], source: nhs },
  { type: 'safety', title: 'Heat and medication', slug: 'heat-and-medication', answer: 'Some medicines can affect hydration, sweating, alertness or temperature regulation, but do not stop prescribed medicine without professional advice.', steps: ['Continue medicines as prescribed.', 'Check storage instructions.', 'Ask a pharmacist or clinician about individual risk.', 'Follow existing advice if your fluids are restricted.'], concepts: ['medication', 'dehydration'], source: medicines },
];

function makeArticle(draft: Draft): Article {
  const source = draft.source ?? home;
  return { title: draft.title, slug: draft.slug, description: draft.answer, articleType: draft.type, concepts: draft.concepts, shortAnswer: draft.answer, sections: [
    { heading: draft.type === 'science' ? 'The simple explanation' : draft.type === 'decision' ? 'How to choose' : 'What to do', steps: draft.steps },
    { heading: 'Why it works', paragraphs: [`This advice follows ${source.organisation} guidance and the underlying principles of ${draft.concepts.join(' and ')}.`] },
    { heading: 'Important exceptions', paragraphs: [draft.type === 'safety' ? 'This page cannot diagnose anyone. Follow the linked health guidance and seek urgent help for emergency symptoms.' : 'Safety, health, weather and the design of your home can change what is appropriate. Stop if an action makes conditions worse.'] },
  ], relatedScience: [], relatedActions: [], relatedDecisions: [], relatedSituations: [], relatedSafety: draft.type === 'safety' ? [] : ['heat-exhaustion-vs-heatstroke'], showCoolingTool: Boolean(draft.showTool), sources: [source], datePublished: reviewed, dateReviewed: reviewed };
}

export const additionalArticles = drafts.map(makeArticle);
