export type ArticleType = 'action' | 'decision' | 'situation' | 'science' | 'safety';
export type Source = { organisation: string; title: string; url: string; type: 'official guidance' | 'health guidance'; accessed: string; supports: string };
export type ArticleSection = { heading: string; paragraphs?: string[]; steps?: string[]; callout?: { tone: 'warning' | 'emergency'; title: string; text: string } };
export type Article = { title: string; slug: string; description: string; articleType: ArticleType; concepts: string[]; shortAnswer: string; sections: ArticleSection[]; relatedScience: string[]; relatedActions: string[]; relatedDecisions: string[]; relatedSituations: string[]; relatedSafety: string[]; showCoolingTool: boolean; sources: Source[]; datePublished: string; dateReviewed: string };

const reviewed = '2026-08-21';
const ukhsaHome: Source = { organisation: 'UK Health Security Agency', title: 'Beat the heat: keep cool at home checklist', url: 'https://www.gov.uk/government/publications/beat-the-heat-hot-weather-advice/beat-the-heat-keep-cool-at-home-checklist', type: 'official guidance', accessed: reviewed, supports: 'Window timing, shading, ventilation, reducing internal heat and identifying higher-risk homes.' };
const nhsHeat: Source = { organisation: 'NHS', title: 'Heat exhaustion and heatstroke', url: 'https://www.nhs.uk/conditions/heat-exhaustion-heatstroke/', type: 'health guidance', accessed: reviewed, supports: 'Symptoms, first response, NHS 111 advice and emergency action.' };

export const articles: Article[] = [
  { title: 'How to cool a room without air conditioning', slug: 'how-to-cool-a-room-without-ac', description: 'Keep heat out during the day, release it when outside cools, and reduce heat made indoors.', articleType: 'action', concepts: ['solar gain', 'ventilation', 'airflow', 'thermal mass'], shortAnswer: 'Shade sunny windows early. Keep them closed while it is hotter outside than inside, then open safe windows when outside becomes cooler. Turn off avoidable heat sources and use a fan to cool people or help move cooler air.', sections: [
    { heading: 'What to do now', steps: ['Close curtains, blinds or shutters on windows receiving direct sun.', 'If outside is hotter than your room, keep windows closed for now.', 'Turn off unused lights, computers, ovens and other equipment producing heat.', 'Use a fan across people for relief; it does not refrigerate a closed room.', 'Move to the coolest room available if one room remains much hotter.'] },
    { heading: 'When outside cools', steps: ['Open windows only where it is safe to do so.', 'Open windows on different sides to create a path through the home.', 'If there is only one opening, place a fan near it facing outward to help expel warm air.'] },
    { heading: 'Why it works', paragraphs: ['Shading reduces solar heat entering through glass. Timed ventilation replaces warm indoor air only when outdoor air is cooler. Fans mainly improve personal comfort through moving air and evaporation.'] },
    { heading: 'Important exceptions', callout: { tone: 'warning', title: 'Safety comes first', text: 'Do not leave windows open where they create a fall, security or fire-safety risk. If anyone shows signs of heat illness, cool the person and follow health guidance rather than concentrating only on the room.' } },
  ], relatedScience: ['why-opening-windows-can-make-your-room-hotter', 'how-fans-cool-you'], relatedActions: ['how-to-use-a-fan-effectively'], relatedDecisions: [], relatedSituations: ['how-to-sleep-during-a-heatwave'], relatedSafety: ['heat-exhaustion-vs-heatstroke'], showCoolingTool: true, sources: [ukhsaHome], datePublished: reviewed, dateReviewed: reviewed },
  { title: 'How to use a fan effectively', slug: 'how-to-use-a-fan-effectively', description: 'Aim airflow at people for relief or use a fan with cooler outdoor air to ventilate a room.', articleType: 'action', concepts: ['airflow', 'evaporation', 'ventilation'], shortAnswer: 'For immediate comfort, direct the airflow across people. To cool a room after outside temperatures fall, use the fan to support a safe route for cooler air in and warmer air out.', sections: [
    { heading: 'Choose the job', steps: ['Personal cooling: point the fan so air moves across exposed skin.', 'Night ventilation: open safe windows once outside is cooler and place a fan near one opening to move warm air out.', 'With air conditioning: use a fan to circulate cooled air, while keeping windows closed.'] },
    { heading: 'What a fan cannot do', paragraphs: ['A normal fan does not lower the temperature of a sealed room. Its motor adds a small amount of heat, so switch it off when nobody benefits from the airflow.'] },
    { heading: 'Important exceptions', callout: { tone: 'warning', title: 'Very high heat needs extra care', text: 'A fan alone may not prevent heat illness in extreme temperatures. Move to a cooler place and follow current public-health advice, especially for higher-risk people.' } },
  ], relatedScience: ['how-fans-cool-you'], relatedActions: ['how-to-cool-a-room-without-ac'], relatedDecisions: [], relatedSituations: ['how-to-sleep-during-a-heatwave'], relatedSafety: ['heat-exhaustion-vs-heatstroke'], showCoolingTool: true, sources: [ukhsaHome], datePublished: reviewed, dateReviewed: reviewed },
  { title: 'How fans cool you', slug: 'how-fans-cool-you', description: 'Fans usually cool people by increasing evaporation and heat transfer—not by making a closed room colder.', articleType: 'science', concepts: ['airflow', 'evaporation', 'personal cooling'], shortAnswer: 'Moving air helps sweat and water evaporate from your skin and carries away some body heat. That is why a fan can make you feel cooler even when the room thermometer barely changes.', sections: [
    { heading: 'The simple explanation', paragraphs: ['Your skin warms the thin layer of air next to it. A fan replaces that air and helps moisture evaporate. Both processes can increase heat loss from your body.'] },
    { heading: 'Why humidity matters', paragraphs: ['Evaporation becomes less effective as the air gets more humid. Moving air may still feel helpful, but it cannot remove the underlying heat or humidity from a closed room.'] },
    { heading: 'Room cooling is a different job', paragraphs: ['To lower room temperature with a fan, you need access to cooler air. Once it is cooler outside, a fan can support ventilation by moving warm indoor air out and drawing cooler air through another opening.'] },
    { heading: 'Limits', callout: { tone: 'warning', title: 'Do not rely on airflow alone in extreme heat', text: 'Public-health guidance places limits on fan use at very high temperatures. Check current local advice and move vulnerable people to a cooler place when possible.' } },
  ], relatedScience: ['why-opening-windows-can-make-your-room-hotter'], relatedActions: ['how-to-use-a-fan-effectively', 'how-to-cool-a-room-without-ac'], relatedDecisions: [], relatedSituations: ['how-to-sleep-during-a-heatwave'], relatedSafety: ['heat-exhaustion-vs-heatstroke'], showCoolingTool: false, sources: [ukhsaHome], datePublished: reviewed, dateReviewed: reviewed },
  { title: 'Why opening windows can make your room hotter', slug: 'why-opening-windows-can-make-your-room-hotter', description: 'Open windows exchange air; whether that cools the room depends on which side is cooler.', articleType: 'science', concepts: ['ventilation', 'airflow', 'temperature difference'], shortAnswer: 'An open window does not automatically cool a room. If the air outside is hotter, ventilation can replace cooler indoor air with hotter air. Open up when outside becomes cooler instead.', sections: [
    { heading: 'Use the temperature difference', paragraphs: ['During the hottest part of the day, shade the glass and keep hotter outdoor air out. In the evening or early morning, open safe windows when the outdoor air is cooler than the indoor air.'] },
    { heading: 'Create a route', paragraphs: ['Air exchange is stronger when air can enter on one side and leave on another. With a single window, an outward-facing fan near the opening can help remove warm indoor air when cooler replacement air can enter.'] },
    { heading: 'Important exceptions', paragraphs: ['Wind, pollution, noise, security, window safety and indoor moisture can change what is practical. Air conditioning also works best with windows closed.'] },
  ], relatedScience: ['how-fans-cool-you'], relatedActions: ['how-to-cool-a-room-without-ac', 'how-to-use-a-fan-effectively'], relatedDecisions: [], relatedSituations: ['how-to-sleep-during-a-heatwave'], relatedSafety: [], showCoolingTool: true, sources: [ukhsaHome], datePublished: reviewed, dateReviewed: reviewed },
  { title: 'How to sleep during a heatwave', slug: 'how-to-sleep-during-a-heatwave', description: 'Cool the bedroom before bed, cool yourself, and use the coolest safe sleeping space available.', articleType: 'situation', concepts: ['night ventilation', 'personal cooling', 'thermal mass'], shortAnswer: 'Keep daytime heat out, then ventilate once outside is cooler. Use light bedding, airflow and cool water for personal relief. If another safe room is cooler, sleep there temporarily.', sections: [
    { heading: 'Before bed', steps: ['Shade sunny bedroom windows during the day.', 'Turn off equipment that adds heat.', 'Once outside is cooler, open safe windows and move air through the home.', 'Prepare cool water and use light bedding and clothing.'] },
    { heading: 'If the room stays hot', paragraphs: ['Walls, roofs and furniture can release stored heat after sunset. Continue safe ventilation while outside remains cooler. Use a fan across people for comfort, or move to a cooler part of the home.'] },
    { heading: 'Check the person, not only the room', callout: { tone: 'warning', title: 'Look for heat illness', text: 'Dizziness, headache, nausea, heavy sweating, thirst, cramps or weakness can be warning signs. Follow NHS advice and get urgent help for possible heatstroke.' } },
  ], relatedScience: ['how-fans-cool-you', 'why-opening-windows-can-make-your-room-hotter'], relatedActions: ['how-to-cool-a-room-without-ac', 'how-to-use-a-fan-effectively'], relatedDecisions: [], relatedSituations: [], relatedSafety: ['heat-exhaustion-vs-heatstroke'], showCoolingTool: true, sources: [ukhsaHome, nhsHeat], datePublished: reviewed, dateReviewed: reviewed },
  { title: 'Heat exhaustion vs heatstroke', slug: 'heat-exhaustion-vs-heatstroke', description: 'Recognise heat exhaustion, start cooling, and know when possible heatstroke requires emergency help.', articleType: 'safety', concepts: ['heat illness', 'first response', 'emergency'], shortAnswer: 'Heat exhaustion needs prompt cooling and fluids. Heatstroke is a medical emergency. Call 999 for signs such as confusion, loss of coordination, seizure, loss of consciousness, very high temperature, or hot skin that is not sweating.', sections: [
    { heading: 'Signs of heat exhaustion', steps: ['Tiredness, dizziness or headache', 'Nausea or vomiting', 'Heavy sweating with pale or clammy skin', 'Cramps, thirst, irritability or a high temperature'] },
    { heading: 'What to do', steps: ['Move the person to a cool place and stay with them.', 'Remove unnecessary clothing.', 'Give cool water if they can drink.', 'Cool their skin with cool water and airflow. Use cold packs wrapped in cloth under the armpits or on the neck.'] },
    { heading: 'When it is an emergency', callout: { tone: 'emergency', title: 'Call 999 for possible heatstroke', text: 'Call 999 if the person is still unwell after 30 minutes of cooling and fluids, or has a very high temperature, hot skin without sweating, fast breathing, confusion, poor coordination, a seizure or loss of consciousness. Follow the call handler’s instructions.' } },
    { heading: 'About this guidance', paragraphs: ['This page cannot diagnose anyone. If you are struggling to treat heat-exhaustion symptoms or need advice, contact NHS 111.'] },
  ], relatedScience: ['how-fans-cool-you'], relatedActions: ['how-to-cool-a-room-without-ac'], relatedDecisions: [], relatedSituations: ['how-to-sleep-during-a-heatwave'], relatedSafety: [], showCoolingTool: false, sources: [nhsHeat, ukhsaHome], datePublished: reviewed, dateReviewed: reviewed },
];

export const articleBySlug = new Map(articles.map(article => [article.slug, article]));
export function validateArticles() {
  const validTypes: ArticleType[] = ['action', 'decision', 'situation', 'science', 'safety']; const slugs = new Set<string>();
  for (const article of articles) { if (!validTypes.includes(article.articleType)) throw new Error(`Invalid article type: ${article.slug}`); if (slugs.has(article.slug)) throw new Error(`Duplicate article slug: ${article.slug}`); slugs.add(article.slug); if (!article.sources.length) throw new Error(`Article has no sources: ${article.slug}`); for (const source of article.sources) if (!source.organisation || !source.title || !source.url || !source.supports || !source.accessed) throw new Error(`Incomplete source: ${article.slug}`); }
  for (const article of articles) for (const link of [...article.relatedScience, ...article.relatedActions, ...article.relatedDecisions, ...article.relatedSituations, ...article.relatedSafety]) if (!slugs.has(link)) throw new Error(`Broken article link: ${article.slug} -> ${link}`);
}
validateArticles();
